### ISSUE TITLE
Gist for sample code to save old log files

### ISSUE THREAD

**Issue by SteveKing** [Dreadbot/Dreadbot-VI#1]
Making this an issue because there's no good way to send messages on github.  This code is really C rather than C++, but it works.  Tested on my Mac and compiled without error when I pasted it into the robot code.

https://gist.github.com/SteveKing/d4fc26fa9e260d3195c3

**Comment by C7C8** [comment]
Added in 71cda5ee927e20a9ca68e4ccbe46e896b3c26683. Thanks!
